remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - Software Engineer
  - Software Developer
  - Application Developer
  - Web Developer
  - Frontend Developer
  - Full Stack Developer

locations:
  - United States
  - USA
  - US
  - New York
  - California
  - Texas
  - Florida
  - Illinois
  - Pennsylvania

distance: 100

companyBlacklist:
  - Google
  - Microsoft
  - Meta
  - Amazon
  - Apple

titleBlacklist:
  - Sales
  - Marketing
